name: Verify

# Controls when the action will run.
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true        
      AWS_SECRET_ACCESS_KEY:
        required: true   
      AWS_CLUSTER_USERNAME:
        required: true              
      AWS_CLUSTER_PASSWORD:
        required: true              
      PORTWORX_SPEC:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    container: quay.io/cloudnativetoolkit/terraform:v1.1

    strategy:
      matrix:
        testcase:
          - aws_portworx_gitops
      fail-fast: false

    env:
      HOME: /home/devops

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Verify deploy on ${{ matrix.testcase }}
        uses: cloud-native-toolkit/action-module-verify-deploy@main
        with:
          clusterId: ${{ matrix.testcase }}
          validateDeployScript: .github/scripts/validate-deploy.sh
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_cluster_username: ${{ secrets.AWS_CLUSTER_USERNAME }}
          TF_VAR_cluster_password: ${{ secrets.AWS_CLUSTER_PASSWORD }}
          TF_VAR_portworx_spec: ${{ secrets.PORTWORX_SPEC }}

      - name: Verify destroy on ${{ matrix.testcase }}
        uses: cloud-native-toolkit/action-module-verify-destroy@main
        if: ${{ always() }}
        with:
          clusterId: ${{ matrix.testcase }}
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_cluster_username: ${{ secrets.AWS_CLUSTER_USERNAME }}
          TF_VAR_cluster_password: ${{ secrets.AWS_CLUSTER_PASSWORD }}
          TF_VAR_portworx_spec: ${{ secrets.PORTWORX_SPEC }}

